ALTER TYPE "AdminAuditAction" ADD VALUE 'BOOKINGS_VIEWED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'PAYMENTS_VIEWED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'USERS_VIEWED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SUMMARY_VIEWED';

ALTER TABLE "admin_audit_logs" ALTER COLUMN "resource_id" DROP NOT NULL;
