ALTER TYPE "SubjectLevel" ADD VALUE IF NOT EXISTS 'PRIMARY';
ALTER TYPE "SubjectLevel" ADD VALUE IF NOT EXISTS 'LOWER_SECONDARY';
ALTER TYPE "SubjectLevel" ADD VALUE IF NOT EXISTS 'HIGH_SCHOOL';
ALTER TYPE "SubjectLevel" ADD VALUE IF NOT EXISTS 'UNIVERSITY';
