import type { AdminTutorListItem, TutorProfile } from "@/lib/tutor-api";

export const mockTutorProfile: TutorProfile = {
  id: "tutor-1",
  userId: "user-1",
  fullName: "Nguyễn Văn A",
  email: "nguyenvana@email.com",
  phone: "0912 345 678",
  avatarUrl: null,
  headline: "Gia sư Toán THPT chuyên luyện thi",
  bio: "Sinh viên năm cuối Đại học Sư Phạm TP.HCM, chuyên ngành Sư phạm Toán. Đã có kinh nghiệm kèm cặp nhiều học sinh đạt điểm cao trong các kỳ thi đại học. Phương pháp giảng dạy tập trung vào việc hiểu bản chất vấn đề, không học vẹt, đồng hành cùng học sinh như một người bạn.",
  introVideoUrl: null,
  experienceYears: 5,
  hourlyRate: "250.000",
  teachingMode: "BOTH",
  locationCity: "TP. Hồ Chí Minh",
  locationDistrict: "Quận 1",
  verificationStatus: "PENDING_REVIEW",
  verificationSubmittedAt: "2026-05-20T10:30:00.000Z",
  approvedAt: null,
  rejectedAt: null,
  rejectionReason: null,
  subjects: [
    {
      id: "ts-1",
      level: "EXAM_PREP",
      subject: { id: "math", name: "Toán học", slug: "toan-hoc", category: "STEM", isActive: true },
    },
    {
      id: "ts-2",
      level: "ADVANCED",
      subject: { id: "physics", name: "Vật lý", slug: "vat-ly", category: "STEM", isActive: true },
    },
  ],
  documents: [
    {
      id: "doc-1",
      type: "NATIONAL_ID_FRONT",
      status: "APPROVED",
      fileName: "cccd_mat_truoc.jpg",
      filePath: "#",
      mimeType: "image/jpeg",
      fileSizeBytes: 1200000,
      rejectionReason: null,
      reviewedAt: null,
    },
    {
      id: "doc-2",
      type: "NATIONAL_ID_BACK",
      status: "APPROVED",
      fileName: "cccd_mat_sau.jpg",
      filePath: "#",
      mimeType: "image/jpeg",
      fileSizeBytes: 1100000,
      rejectionReason: null,
      reviewedAt: null,
    },
    {
      id: "doc-3",
      type: "DEGREE",
      status: "PENDING",
      fileName: "bang_dai_hoc_sp.pdf",
      filePath: "#",
      mimeType: "application/pdf",
      fileSizeBytes: 2400000,
      rejectionReason: null,
      reviewedAt: null,
    },
  ],
};

export const adminTutorRows: AdminTutorListItem[] = [
  {
    id: "tutor-1",
    fullName: "Nguyễn Thị Mai",
    email: "mai.nguyen@email.com",
    avatarUrl: null,
    city: "Hà Nội",
    district: "Cầu Giấy",
    subjectCount: 3,
    documentCount: 4,
    submittedAt: "2026-05-19T09:15:00.000Z",
    status: "PENDING_REVIEW",
  },
  {
    id: "tutor-2",
    fullName: "Trần Văn Nam",
    email: "nam.tran99@email.com",
    avatarUrl: null,
    city: "TP.HCM",
    district: "Quận 1",
    subjectCount: 2,
    documentCount: 2,
    submittedAt: "2026-05-18T14:20:00.000Z",
    status: "PENDING_REVIEW",
  },
  {
    id: "tutor-3",
    fullName: "Lê Thu Hà",
    email: "ha.le.math@email.com",
    avatarUrl: null,
    city: "Hà Nội",
    district: "Đống Đa",
    subjectCount: 1,
    documentCount: 5,
    submittedAt: "2026-05-18T08:45:00.000Z",
    status: "PENDING_REVIEW",
  },
  {
    id: "tutor-4",
    fullName: "Phạm Hoàng Anh",
    email: "hoanganh.p@email.com",
    avatarUrl: null,
    city: "Đà Nẵng",
    district: "Hải Châu",
    subjectCount: 4,
    documentCount: 8,
    submittedAt: "2026-05-17T16:00:00.000Z",
    status: "PENDING_REVIEW",
  },
];
